version: "3"

services:
  node-hp-scan-to:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-hp-scan-to
    hostname: scan
    environment:
      - IP=10.98.10.31
      - PATTERN="scan"_dd.mm.yyyy_hh:MM:ss
      - PGID=100
      - PUID=1026
      - TZ=Europe/Amsterdam
    volumes:
      - /volume1/docker/paperlessngx/consume:/scan
    restart: always
